/// Flutter icons CustomIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData tools = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData playlist_add = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData check = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData find_in_page = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clipboard = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData dot_3 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData apartment = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData file_add = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xf083, fontFamily: _kFontFam);
  static const IconData doc_text = const IconData(0xf0f6, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xf118, fontFamily: _kFontFam);
  static const IconData file_pdf = const IconData(0xf1c1, fontFamily: _kFontFam);
  static const IconData file_word = const IconData(0xf1c2, fontFamily: _kFontFam);
  static const IconData file_excel = const IconData(0xf1c3, fontFamily: _kFontFam);
}
